import argparse
import re
from pathlib import Path


def slugify(title: str) -> str:
    title = title.strip().lower()
    title = re.sub(r"[^a-z0-9]+", "_", title)
    title = re.sub(r"_+", "_", title).strip("_")
    return title or "section"


def normalize_heading(raw: str) -> str:
    raw = raw.strip()
    # Strip leading list marker if present.
    raw = re.sub(r"^[-*]\s+", "", raw)
    # Drop leading numbering like "1." or "1)".
    raw = re.sub(r"^\d+\s*[\.)]\s*", "", raw)
    return raw.strip()


SKIP_HEADINGS = {
    "abstract",
    "table of contents",
    "tables",
    "table of figures",
    "discussion references",
    "references",
}


def is_probably_heading(text: str) -> bool:
    # Reject very long "sentence" lines that slipped into outline.
    if len(text) > 140:
        return False
    return True


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate arxiv_robust section stubs from scratch/outline.md")
    parser.add_argument(
        "--outline",
        default=str(Path(__file__).resolve().parents[1] / "scratch" / "outline.md"),
        help="Path to outline.md",
    )
    parser.add_argument(
        "--sections-dir",
        default=str(Path(__file__).resolve().parents[1] / "sections"),
        help="Directory to write section .tex files",
    )
    parser.add_argument(
        "--includes",
        default=str(Path(__file__).resolve().parents[1] / "sections" / "00_includes.tex"),
        help="Path to write includes file",
    )

    args = parser.parse_args()

    outline_path = Path(args.outline)
    sections_dir = Path(args.sections_dir)
    includes_path = Path(args.includes)

    sections_dir.mkdir(parents=True, exist_ok=True)

    lines = outline_path.read_text(encoding="utf-8").splitlines()

    top_level: list[str] = []
    for line in lines:
        if not line.strip():
            continue
        if not line.startswith("- "):
            continue
        if line.startswith("  "):
            continue  # only top-level

        raw_heading = normalize_heading(line)
        if not raw_heading:
            continue

        key = raw_heading.strip().lower().rstrip(":")
        if key in SKIP_HEADINGS:
            continue
        if not is_probably_heading(raw_heading):
            continue

        top_level.append(raw_heading)

    # Partition into main sections vs appendices.
    main_sections: list[str] = []
    appendices: list[str] = []
    for h in top_level:
        if h.lower().startswith("appendix"):
            appendices.append(h)
        else:
            main_sections.append(h)

    # Numbered filename prefixes for stable ordering.
    output_files: list[tuple[str, Path]] = []

    def write_stub(idx: int, heading: str) -> Path:
        title = heading
        fname = f"{idx:02d}_{slugify(title)[:60]}.tex"
        path = sections_dir / fname
        if not path.exists():
            path.write_text(
                "\\section{" + title.replace("{", "\\{").replace("}", "\\}") + "}\n\n"
                "% TODO: Port content from scratch/body_dump.tex and check against the PDF.\n",
                encoding="utf-8",
            )
        return path

    includes_lines: list[str] = []
    includes_lines.append("% AUTO-GENERATED by scripts/generate_section_skeleton_from_outline.py")
    includes_lines.append("% Edit the individual section files; re-run generator only to add missing stubs.")
    includes_lines.append("")

    idx = 10
    for heading in main_sections:
        path = write_stub(idx, heading)
        rel = path.with_suffix("").as_posix().split("/sections/")[-1]
        includes_lines.append(f"\\input{{sections/{rel}}}")
        output_files.append((heading, path))
        idx += 1

    if appendices:
        includes_lines.append("")
        includes_lines.append("\\appendix")
        includes_lines.append("")

        idx = 90
        for heading in appendices:
            path = write_stub(idx, heading)
            rel = path.with_suffix("").as_posix().split("/sections/")[-1]
            includes_lines.append(f"\\input{{sections/{rel}}}")
            output_files.append((heading, path))
            idx += 1

    includes_path.write_text("\n".join(includes_lines) + "\n", encoding="utf-8")

    print(f"Wrote includes: {includes_path}")
    print("Section stubs:")
    for heading, path in output_files:
        print(f"- {heading} -> {path.name}")


if __name__ == "__main__":
    main()
